# Generated by Django 3.0.3 on 2020-03-18 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_training', models.IntegerField(choices=[(1, 'Бюджетная'), (2, 'Комерческая')], default=1, verbose_name='Форма обучения')),
                ('type_training', models.IntegerField(choices=[(1, 'Не сокращенная'), (2, 'Сокращенная')], default=1, verbose_name='Не сокращенная/Сокращенная')),
            ],
            options={
                'verbose_name': 'Академическая группа',
                'verbose_name_plural': 'Академические группы',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.IntegerField(blank=True, null=True, verbose_name='ID факультета')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное наименование')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Общежитие',
                'verbose_name_plural': 'Общежития',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('gender', models.IntegerField(choices=[(1, 'Женский'), (2, 'Мужской')], verbose_name='Пол')),
                ('birth_place', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес по прописке')),
                ('address_fact', models.CharField(max_length=255, verbose_name='Адрес фактический')),
                ('series', models.IntegerField(verbose_name='Серия пасспорта')),
                ('number', models.IntegerField(verbose_name='Номер пасспорта')),
                ('form_training', models.IntegerField(choices=[(1, 'Бюджетная'), (2, 'Комерческая')], verbose_name='Форма обучения')),
                ('disability_group', models.IntegerField(blank=True, choices=[(1, '1 группа'), (2, '2 группа'), (3, '3 группа')], null=True, verbose_name='Форма инвалидности')),
                ('is_orphan', models.BooleanField(default=False, verbose_name='Студенты-сироты и студенты, оставшихся без попечения родителей')),
                ('is_military', models.BooleanField(default=False, verbose_name='Студенты-ветераны и инвалиды боевых действий')),
                ('is_radioactive', models.BooleanField(default=False, verbose_name='Студенты из районов, подвергшихся радиоактивному заражению')),
                ('is_parents_retired', models.BooleanField(default=False, verbose_name='Студенты, у которых оба родителя пенсионеры')),
                ('is_parents_disabilities', models.BooleanField(default=False, verbose_name='Студенты, у которых родители - инвалиды')),
                ('is_many_kids_family', models.BooleanField(default=False, verbose_name='Студенты из многодетных семей')),
                ('is_from_broken_home', models.BooleanField(default=False, verbose_name='Студенты из неполных семей')),
                ('is_poor', models.BooleanField(default=False, verbose_name='Относится к категории малообеспеченных')),
                ('is_chronic_disease', models.BooleanField(default=False, verbose_name='Студенты, страдающих хроническими заболеваниями')),
                ('is_wed', models.BooleanField(default=False, verbose_name='Студенты, состоящие в браке')),
                ('is_status_student_family', models.BooleanField(default=False, verbose_name="Имеют статус 'студенческая семья'")),
                ('is_have_kids', models.BooleanField(default=False, verbose_name='Студенты, имеющие детей')),
                ('is_unwed_mother', models.BooleanField(default=False, verbose_name='В том числе матери-одиночки')),
                ('is_south_east_ukraine', models.BooleanField(default=False, verbose_name='Студенты, прибывшие на обучение из Юго-востока Украины')),
                ('academic_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.AcademicGroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='ResidenceHostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(blank=True, null=True, verbose_name='Номер комнаты')),
                ('is_family', models.BooleanField(default=False, verbose_name='Семейная комната')),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Hostel', verbose_name='Общежитие')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Проживающий в общежитии',
                'verbose_name_plural': 'Проживающие в общежитии',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('work', models.CharField(max_length=255, verbose_name='Место работы, должность')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('kid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Student', verbose_name='Ребёнок')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное наименование')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Department', verbose_name='Кафедра'),
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Тьютор'),
        ),
    ]
