# Generated by Django 3.0.5 on 2020-04-20 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Гражданство',
                'verbose_name_plural': 'Гражданства',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Национальность',
                'verbose_name_plural': 'Национальности',
            },
        ),
        migrations.CreateModel(
            name='NativeLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Родной язык',
                'verbose_name_plural': 'Родные языки',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='form_training',
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='letters',
            field=models.CharField(default='', max_length=6, verbose_name='Сокращенное наименование группы'),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_training',
            field=models.IntegerField(choices=[(0, 'Не выбрано'), (1, 'Бюджетная'), (2, 'Комерческая')], default=0, verbose_name='Способ финансирования'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='system.AcademicGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(default='', max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='сuratorhour',
            name='room',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Аудитория'),
        ),
        migrations.CreateModel(
            name='IndividualWorkWithStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=255, verbose_name='Проблема')),
                ('solution', models.CharField(max_length=255, verbose_name='Решение')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Student', verbose_name='Общежитие')),
            ],
            options={
                'verbose_name': 'Индивидуальная работа со студентами',
                'verbose_name_plural': 'Индивидуальные работы со студентами',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Citizenship', verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Nationality', verbose_name='Национальность'),
        ),
        migrations.AddField(
            model_name='student',
            name='native_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.NativeLanguage', verbose_name='Родной язык'),
        ),
    ]
