# Generated by Django 3.0.5 on 2020-04-23 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200420_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualworkwithstudents',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.AcademicGroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='visithostel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.AcademicGroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='сuratorhour',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.AcademicGroup', verbose_name='Группа'),
        ),
    ]
