# Generated by Django 3.0.5 on 2020-06-09 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200423_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letters', models.CharField(max_length=25, verbose_name='Символы')),
                ('code', models.CharField(max_length=25, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Направление')),
                ('target', models.CharField(max_length=255, verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.AddField(
            model_name='academicgroup',
            name='training_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.TrainingDirection', verbose_name='Направление'),
        ),
    ]
