# Generated by Django 3.0.5 on 2020-06-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200609_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active_group',
            field=models.IntegerField(choices=[(0, 'Отсутствует'), (1, 'Староста'), (2, 'Профгруппорг')], default=0, verbose_name='Актив группы'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(default='', max_length=25, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='work',
            field=models.CharField(default='', max_length=255, verbose_name='Место работы, должность'),
        ),
        migrations.AlterField(
            model_name='residencehostel',
            name='room',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес по прописке'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_fact',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес фактический'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_place',
            field=models.CharField(default='', max_length=255, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='disability_group',
            field=models.IntegerField(blank=True, choices=[(0, 'Отсутствует'), (1, '1 группа'), (2, '2 группа'), (3, '3 группа')], default=0, null=True, verbose_name='Форма инвалидности'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(default='', max_length=6, verbose_name='Номер пасспорта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(default='', max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_training',
            field=models.IntegerField(choices=[(1, 'Бюджетная'), (2, 'Комерческая')], default=0, verbose_name='Способ финансирования'),
        ),
        migrations.AlterField(
            model_name='student',
            name='series',
            field=models.CharField(default='', max_length=6, verbose_name='Серия пасспорта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(default='', max_length=50, verbose_name='Фамилия'),
        ),
    ]
