# Generated by Django 3.0.5 on 2020-06-24 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200612_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicgroup',
            name='letters',
        ),
    ]
