# Generated by Django 3.0.5 on 2020-04-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_proxyblacklistedtoken_proxyoutstandingtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=1, verbose_name='Роль'),
        ),
    ]
