# Generated by Django 3.0.5 on 2020-06-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_auto_20200420_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employe_position',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность сотрудника'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Тютор'), (2, 'Зам декана по в.р.'), (3, 'Администратор')], default=1, verbose_name='Роль'),
        ),
    ]
