# Generated by Django 3.0.5 on 2020-06-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_auto_20200607_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Тютор'), (2, 'Контроль работы'), (3, 'Администратор')], default=1, verbose_name='Роль'),
        ),
    ]
